---
title: "Access Remote Computer"
author: "David Colameo"
format: html
editor: visual
---

## Welcome To MaxTwo

This is a short tutorial describing how to access and setup the MaxTwo System. You will need to have access to our remote Linux Computer and Cell Culture System as well as have excitable cells growing on 6- or 24-well MaxTwo plates.

### Before starting!:

-   Always make sure to book the system on [EZBooking](https://booking.core.uzh.ch/cgi-bin/AGS_Login.cgi). If you don't have access to the booking system, contact a staff member.

-   Turn on the MaxTwo recorder and gas mixer (located underneath the microscope on a small incubator).

<!-- -->

-   Make sure to let the MaxTwo recorder warm up for 10-15min and the gas mixer to calibrate to 5% CO2. If it is not possible to come by sooner, you can ask a staff member to turn it on for you (some time in advance).

### Place Plate into the Recorder

-   Click once on the blue button (touchscreen style, does not need much force)

-   Place the plate into the recorder, make sure the two notches on the upper short side aligns with the the holes on the plate.

-   Double-click on the blue button (alternatively, this can be done also from the software).

-   Close the recorder by clicking one time on the blue button.

-   If you have a 6-well plate, make sure to remember the unique ID of your plate.

### Access the Linux Computer

In order to access the recording Linux Computer, you will need to have access to Citrix. There are several ZMB tutorials on how to do it for the first on [Windows](https://zmb.dozuki.com/Guide/Installation+of+Citrix+Workspace+app+-+Windows/243?lang=en), [Mac](https://zmb.dozuki.com/Guide/Installation+of+Citrix+Workspace+app+-+Mac/244?lang=en) or [Linux](https://zmb.dozuki.com/Guide/Installation+of+Citrix+Workspace+app+-+Linux/245).

Click on "EPHAC MaxTwo VM" and connect to the PC via Remote Desktop (RDP). See below for troubleshooting if something goes wrong.

The username and password of the remote computer will be communicated to you separately.

Good to know:

If you are connected to the UZH intranet either directly or through VPN, you can also access the remote computer via RDP. This allows you to set custom resolutions for your display.

### Start MaxLab Live Scope

If you find the programs on from a previous user, make sure to close everything and start fresh every time. First, connect to the MaxTwo Recorder by clicking on "Server" on the Desktop, then open the MaxLab Live Program called "Scope".

You will need to initiate the plate by clicking on "Initiate" (close to left bottom corner). If you own a 24-well plate, it will recognize the plate id automatically. Still make sure the plate id matches yours, as in rare instances it reports the previously recorded plate. If you own a 6-well plate, type in your ID.

Click on "Offset" and observe the Offset Histogram close to the right-upper corner becoming tighter.

Now you are ready to start a recording. Happy Spiking!!

## Troubleshooting:

#### I cannot see the Citrix Icon of the Linux Computer:

-   Refresh Apps on Citrix (Wheel Cog Icon, upper right corner)

-   If problems persists, restart your computer and make sure you are on the newest Citrix version.

-   Try to connect to the browser version of [Citrix](https://vdi.core.uzh.ch/logon/LogonPoint/index.html).

-   Contact a staff member or the IT department of the ZMB.

#### The Linux Computer is very slow to respond or the display does not show the whole window:

This is a known issue with Macs and/or large monitor displays (4K monitors). Contact staff for workaround.

#### I got thrown out of the program and now it says that Number of Sessions have been reached:

Close down Citrix and wait 5mins before reconnecting. As an alternative, use RDP directly to connect to the Linux Computer, especially if this problem persists or repeats itself.

#### I cannot set the Offset or the Plate ID is wrong (24-well plate only):

-   Close MaxLab and Server connection, restart and reconnect.

-   If problem persists, reseat the plate in the MaxTwo Recorder.

    -   This can be done from MaxLab. Click on the icon that looks like the MaxTwo recorder, then click on Unlock Plate and re-lock it. You might need to close and reopen the program one more time.

    -   Alternatively, do it physically on the recorder by double-click on the button.
